default: &default
  adapter: postgresql
  database: tt-base
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default

production:
  <<: *default
  uri: <%= ENV["DATABASE_URL"] %>

testing:
  <<: *default
  uri: <%= ENV["DATABASE_URL"] %>
