# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af153ac8d106988f5615a74ac64ec82b4e880407a227a3f3116fe9cb981e38c75ff41625398fe7dc99d09e3f0af96ea09d079141af9199f8457f31a96de1f50

test:
  secret_key_base: 1739d2ca8b77e02e3148a857770e708129c567dc2605d70e881ef128971a637891c9463adcee0dced18ab9dca65521059cb8c8a1ddcdb39e83120d1321f314ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
